// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQa9RMFSTDOOJtDOWXlfnXtax55D_t-vU',
    appId: '1:453746814738:web:c8e13f522f4c5c7c574dcb',
    messagingSenderId: '453746814738',
    projectId: 'new-walking-school-bus',
    authDomain: 'new-walking-school-bus.firebaseapp.com',
    storageBucket: 'new-walking-school-bus.firebasestorage.app',
    measurementId: 'G-DSXSCBCB0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGyyMQK6wyVK2y9Bq26epHZU1xU4kFpFg',
    appId: '1:453746814738:android:a03e6955818809f8574dcb',
    messagingSenderId: '453746814738',
    projectId: 'new-walking-school-bus',
    storageBucket: 'new-walking-school-bus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkX04sKZak6HipW6sFmKKw-N9kxmihCL4',
    appId: '1:453746814738:ios:887ae087fe990ff6574dcb',
    messagingSenderId: '453746814738',
    projectId: 'new-walking-school-bus',
    storageBucket: 'new-walking-school-bus.firebasestorage.app',
    iosBundleId: 'com.jjungoori.newWalking',
  );
}
